### ISSUE TITLE
undefined symbol error: _ZNK10tensorflow4Node11type_stringEv

### ISSUE THREAD

**Issue by pacifastacus** [tensorflow/ngraph-bridge#204]
I installed ngraph-tensorflow-bridge pip package in a virtualenv by following the readme.
```
virtualenv --system-site-packages -p python3 ngraph-venv
source ./ngraph-venv/bin/activate
pip install -U tensorflow==1.14.0
pip install -U ngraph-tensorflow-bridge
```
After that when i want to import the ngraph_bridge module i get an error:
NotFoundError: /home/***/ngraph-venv/lib/python3.7/site-packages/ngraph_bridge/libngraph_bridge.so: undefined symbol: _ZNK10tensorflow4Node11type_stringEv

My system:
Processor		: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
Memory		: 10114MB (2114MB used)
Operating System		: Debian GNU/Linux 10 (buster)

**Comment by arne0x7** [comment]
I'm getting the same error.

Intel® Core™ i5-6500 CPU @ 3.20GHz × 4
Ubuntu 19.04
Python 3.7.3

**Comment by SleepProgger** [comment]
Same here in an anaconda environment with python 3.6.7.
Happens as soon as ngraph_bridge is imported.

```
# python -c "import ngraph_bridge"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nope/.conda/envs/test/lib/python3.6/site-packages/ngraph_bridge/__init__.py", line 97, in <module>
    _ = load_library.load_op_library(full_lib_path)
  File "/home/nope/.conda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/nope/.conda/envs/test/lib/python3.6/site-packages/ngraph_bridge/libngraph_bridge.so: undefined symbol: _ZNK10tensorflow4Node11type_stringEv
```

System:
CPU: `AMD Ryzen 5 3600 6-Core Processor`(Altho the same thing occurred about a month ago with my old CPU)
OS: Manjaro stable with 5.2.8-1 kernel.

**Comment by drwebb** [comment]
I also had this problem when I was using a tensorflow package install in a conda environment using `conda install`. Using `pip install -U tensorflow==1.14.0` fixed the issue inside the conda environment.
