### ISSUE TITLE
Python3 virtualenv fails to activate during build_ngtf.py run and causes the build to crash.

### ISSUE THREAD

**Issue by ashahba** [tensorflow/ngraph-bridge#383]
Here is the stack trace:
```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ARTIFACTS location: /tmp/ashahba/ngraph-bridge/build_cmake/artifacts
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/ashahba/ngraph-bridge/build_cmake/venv-tf-py3/bin/python3
Also creating executable in /tmp/ashahba/ngraph-bridge/build_cmake/venv-tf-py3/bin/python
Installing setuptools, pip, wheel...
done.
Loading virtual environment from: /tmp/ashahba/ngraph-bridge/build_cmake/venv-tf-py3
Traceback (most recent call last):
  File "./build_ngtf.py", line 524, in <module>
    main()
  File "./build_ngtf.py", line 228, in main
    load_venv(venv_dir)
  File "/tmp/ashahba/ngraph-bridge/tools/build_utils.py", line 126, in load_venv
    dict(__file__=activate_this_file), dict(__file__=activate_this_file))
  File "/tmp/ashahba/ngraph-bridge/build_cmake/venv-tf-py3/bin/activate_this.py", line 46, in <module>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
  File "/tmp/ashahba/ngraph-bridge/build_cmake/venv-tf-py3/bin/activate_this.py", line 46, in <listcomp>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
NameError: name 'prev' is not defined```

**Comment by ashahba** [comment]
I can work on this as my first warmup item 🙂

**Comment by brzegorz** [comment]
Hi! I struggle with the same issue. A fix would be nice: )

**Comment by tinrobot2000** [comment]
Same here. Building with MacOS 10.14.6, Python 3.7.6, ngraph-bridge v0.18.1 and --use_prebuilt_tensorflow [1.14.0] --build_plaidml_backend arguments

**Comment by dbonner** [comment]
To fix this, issue the following in your terminal:
pip3 install virtualenv==16.1.0

The latest version of virtualenv is not compatible with the ngraph build scripts.

I found this out from [](https://github.com/NervanaSystems/he-transformer/issues/130)
