### ISSUE TITLE
Mismatched tensor shapes error only with nGraphBridge+PlaidML. 

### ISSUE THREAD

**Issue by kenthinson** [tensorflow/ngraph-bridge#394]
Hello. I am attempting to use nGraphBridge+PlaidML to run https://github.com/ManishSoni1908/Mobilenet-ssd-keras

If I run the project just on CPU it runs without issues. However if I attempt to run the project with nGraphBridge+PlaidML I get an error about mismatched tensor shapes. Can someone please advise me on this?

Mac OSX 10.15.1
TensorFlow version:  1.14.0
nGraph bridge version: b'0.18.0'
nGraph version used for this build: b'0.25.0+005c118'
TensorFlow version used for this build: v1.14.0-0-g87989f6959
CXX11_ABI flag used for this build: 0
nGraph bridge built with Grappler: False
nGraph bridge built with Variables and Optimizers Enablement: False

```
Epoch 1/500
2019-12-18 23:12:29.244856: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_rewrite_pass.cc:235] NGraph using backend: PLAIDML
2019-12-18 23:12:29.688057: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_rewrite_pass.cc:235] NGraph using backend: PLAIDML
2019-12-18 23:12:34.062976: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_rewrite_pass.cc:235] NGraph using backend: PLAIDML
2019-12-18 23:14:37.455619: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_utils.cc:258] Serializing graph to: tf_function_error_ngraph_cluster_172.json

Traceback (most recent call last):
  File "train_mobilenet_ssd.py", line 285, in <module>
    train(args)
  File "train_mobilenet_ssd.py", line 262, in train
    callbacks=callbacks
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/Users/kent/Developer/ml-venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: Mismatched tensor shapes in elementwise operation: X_T78[32,2,2,64] can't match X_T82[32,2,18446744073709551558,124]
```

I am currently trying to compile a newer version of nGraph-Bridge using the instructions just in case that is the resolution.

**Comment by shukob** [comment]
I have a similar issue for [pose-tensorflow](https://github.com/eldar/pose-tensorflow). 

```
2020-01-29 22:12:25.820939: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_rewrite_pass.cc:235] NGraph using backend: PLAIDML
2020-01-29 22:12:29.351483: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_rewrite_pass.cc:235] NGraph using backend: PLAIDML
2020-01-29 22:13:43.526833: I /jenkins/workspace/tf-ng-bridge-mac-pkg/source/ngraph-packaging/ngraph-tf/ngraph_bridge/ngraph_utils.cc:258] Serializing graph to: tf_function_error_ngraph_cluster_867.json

Traceback (most recent call last):
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: Mismatched tensor shapes in elementwise operation: X_T2[1,90,60,128] can't match X_T9[1,120,18446744073709551610,164]

         [[{{node ngraph_cluster_867}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../train.py", line 144, in <module>
    train()
  File "../../../train.py", line 123, in train
    feed_dict={learning_rate: current_lr})
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/Users/shukob/.conda/envs/pose-tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: Mismatched tensor shapes in elementwise operation: X_T2[1,90,60,128] can't match X_T9[1,120,18446744073709551610,164]

```

**Comment by MarcosJNS** [comment]
I'm having a similar issue, were you able to fix it?

**Comment by kenthinson** [comment]
@MarcosJNS no I ended up booting Ubuntu and using Rcom

**Comment by MarcosJNS** [comment]
Thanks for the quick response, I'll go for Rocm as well

**Comment by shukob** [comment]
No. That was on a MBP. I gave up on it and bought an NVIDIA box.

**Comment by kenthinson** [comment]
Closing due to no response
