### ISSUE TITLE
"build_ngtf.py" errors out if "--use_tensorflow_from_location" is used.

### ISSUE THREAD

**Issue by ashahba** [tensorflow/ngraph-bridge#442]
If I'm running:
```
python3 build_ngtf.py --use_tensorflow_from_location /prebuilt/tf_v1.14.0
```
I get the following error near the end:
```
SUCCESSFULLY generated wheel: ngraph_tensorflow_bridge-0.22.0rc3-py2.py3-none-manylinux1_x86_64.whl
PWD: /ngraph-bridge/build_cmake
Running COMMAND: cp -r /prebuilt/tf_v1.14.0/tensorflow/tensorflow/python /ngraph-bridge/build_cmake/artifacts/tensorflow
cp: cannot overwrite non-directory '/ngraph-bridge/build_cmake/artifacts/tensorflow/python' with directory '/prebuilt/tf_v1.14.0/tensorflow/tensorflow/python'
Traceback (most recent call last):
  File "build_ngtf.py", line 525, in <module>
    main()
  File "build_ngtf.py", line 502, in main
    verbose=True)
  File "/ngraph-bridge/tools/build_utils.py", line 60, in command_executor
    raise Exception("Error running command: " + cmd)
Exception: Error running command: cp -r /prebuilt/tf_v1.14.0/tensorflow/tensorflow/python /ngraph-bridge/build_cmake/artifacts/tensorflow
```

**Comment by ashahba** [comment]
By the way this doesn't happen during first build, but subsequent builds throw this exceptions if code build bits are already in place.

**Comment by zap-wizard** [comment]
`cp: cannot overwrite non-directory '/ngraph-bridge/build_cmake/artifacts/tensorflow/python' with directory '/prebuilt/tf_v1.14.0/tensorflow/tensorflow/python'`

`cp` tries to copy the tensorflow directories again, but fails, because they already exist.
