### ISSUE TITLE
Backend plaidml unavailable

### ISSUE THREAD

**Issue by zap-wizard** [tensorflow/ngraph-bridge#508]
I can't set backend to 'PLAIDML'. Listing backends plaidml shows up, but when trying to set the backend, it fails.
```
>>> ngraph_bridge.list_backends()
['CPU', 'GCPU', 'INTERPRETER', 'NOP', 'PLAIDML']
```

```
>>> ngraph_bridge.set_backend('PLAIDML')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/site-packages/ngraph_bridge/__init__.py", line 179, in set_backend
    raise Exception("Backend " + backend + " unavailable.")
Exception: Backend PLAIDML unavailable.
```
_ngraph-bridge=0.22.0-rc4
plaidml=0.6.4_

**Comment by zap-wizard** [comment]
Ok, solved this. `'PlaidML'` worked instead of `'PLAIDML'`.
```
>>> ngraph_bridge.set_backend('PlaidML')
>>> ngraph_bridge.get_currently_set_backend_name()
'PlaidML'
>>> 
```
This is weird, because if I list all available backends, it outputs 'PLAIDML'. Also in the documentation, 'PLAIDML' is used.
